### ISSUE TITLE
Evaluating empty methods causes exception

### ISSUE THREAD

**Issue by samdphillips** [samdphillips/onyx-rb#1]
This should probably evaluate to nil.  Instead it throws an exception which it shouldn't do.

```smalltalk
Object subclass: Foo [ 
    bar [ 
    ] 
] 

Foo new bar
```

Same for evaluating an empty block:

```smalltalk

[ ] value

```

**Comment by samdphillips** [comment]
The nature of the exceptions makes me think that the best fix is to put the right kind of node in the AST.

    $ ruby -Ilib -r onyx -e main empty1.ost
    /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:22:in `step': undefined method `visit' for nil:NilClass (NoMethodError)
        from /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:151:in `step'
        from /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:146:in `run'
        from /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:120:in `eval'
        from /Users/sphillips/projects/onyx-rb/lib/onyx/runner.rb:9:in `block in run'
        from /Users/sphillips/projects/onyx-rb/lib/onyx/runner.rb:7:in `each'
        from /Users/sphillips/projects/onyx-rb/lib/onyx/runner.rb:7:in `run'
        from /Users/sphillips/projects/onyx-rb/lib/onyx.rb:20:in `main'
        from -e:1:in `<main>'

    $ ruby -Ilib -r onyx -e main empty2.ost
    /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:22:in `step': undefined method `visit' for nil:NilClass (NoMethodError)
        from /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:151:in `step'
        from /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:146:in `run'
        from /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:120:in `eval'
        from /Users/sphillips/projects/onyx-rb/lib/onyx/runner.rb:9:in `block in run'
        from /Users/sphillips/projects/onyx-rb/lib/onyx/runner.rb:7:in `each'
        from /Users/sphillips/projects/onyx-rb/lib/onyx/runner.rb:7:in `run'
        from /Users/sphillips/projects/onyx-rb/lib/onyx.rb:20:in `main'
        from -e:1:in `<main>'
