### ISSUE TITLE
Returning from a block in the top level errors

### ISSUE THREAD

**Issue by samdphillips** [samdphillips/onyx-rb#4]
```
[ ^ true ] value
```

when run causes an exception in the interpreter.

```
/Users/sphillips/projects/onyx-rb/lib/onyx/frame.rb:33:in `[]': no implicit conversion from nil to integer (TypeError)
    from /Users/sphillips/projects/onyx-rb/lib/onyx/frame.rb:33:in `pop'
    from /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:103:in `continue'
    from /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:47:in `step'
    from /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:154:in `step'
    from /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:149:in `run'
    from /Users/sphillips/projects/onyx-rb/lib/onyx/interp.rb:120:in `eval'
    from /Users/sphillips/projects/onyx-rb/lib/onyx/runner.rb:9:in `block in run'
    from /Users/sphillips/projects/onyx-rb/lib/onyx/runner.rb:7:in `each'
    from /Users/sphillips/projects/onyx-rb/lib/onyx/runner.rb:7:in `run'
    from /Users/sphillips/projects/onyx-rb/lib/onyx.rb:21:in `main'
    from -e:1:in `<main>'
```

Possibly because there is no escape continuation set at the top level.  Maybe add a nil check and throwing an appropriate exception.

**Comment by samdphillips** [comment]
One of the places where this may be convenient is at the top level we may have some code within a block that we want to prematurely exit from.  Maybe a form like:

```
'a' printNl.
[ 'b' printNl.
  ^ 'c'.
 'd' printNl ] returnTo printNl.

=>

a
b
c

```

The downside is that some code may seem non-intuitive.
